{"name": "Verify that the order is not accepted if passing invalid courier id.", "status": "passed", "description": "Verify that 404 code is returned for PUT request if courier id is invalid.", "steps": [{"name": "Accept order.", "status": "passed", "parameters": [{"name": "order_id", "value": "437733"}, {"name": "courier_id", "value": "1"}], "start": 1742473783165, "stop": 1742473783545}], "start": 1742473783165, "stop": 1742473783546, "uuid": "f896095d-d44d-417f-b1bb-dc9d2e90023a", "historyId": "53080a96b19a188c2af0a34b2e5a62e1", "testCaseId": "53080a96b19a188c2af0a34b2e5a62e1", "fullName": "tests.test_order_accept.TestOrderAccept#test_accept_order_not_existing_courier_id_not_accepted", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_accept"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "ip-192-168-100-12.eu-north-1.compute.internal"}, {"name": "thread", "value": "48014-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_accept"}]}