{"name": "Verify that the order is not accepted if passing invalid courier id.", "status": "passed", "description": "Verify that 404 code is returned for PUT request if courier id is invalid.", "steps": [{"name": "Accept order.", "status": "passed", "parameters": [{"name": "order_id", "value": "436861"}, {"name": "courier_id", "value": "1"}], "start": 1742386040821, "stop": 1742386041258}], "start": 1742386040821, "stop": 1742386041259, "uuid": "a99d5f52-1b47-415d-8555-d900b823f7af", "historyId": "53080a96b19a188c2af0a34b2e5a62e1", "testCaseId": "53080a96b19a188c2af0a34b2e5a62e1", "fullName": "tests.test_order_accept.TestOrderAccept#test_accept_order_not_existing_courier_id_not_accepted", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_accept"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "ip-192-168-100-6.eu-north-1.compute.internal"}, {"name": "thread", "value": "20517-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_accept"}]}