{"name": "Verify that the order is not accepted if passing invalid order id.", "status": "passed", "description": "Verify that 404 code is returned for PUT request if order id is invalid.", "steps": [{"name": "Accept order.", "status": "passed", "parameters": [{"name": "order_id", "value": "1"}, {"name": "courier_id", "value": "488110"}], "start": 1742473777790, "stop": 1742473778168}], "start": 1742473777790, "stop": 1742473778169, "uuid": "7a43b97b-fca9-4c2b-bc13-6b8097e1a91f", "historyId": "b4c9234cacfec96600d4d671569cae0d", "testCaseId": "b4c9234cacfec96600d4d671569cae0d", "fullName": "tests.test_order_accept.TestOrderAccept#test_accept_order_not_existing_order_id_not_accepted", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_accept"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "ip-192-168-100-12.eu-north-1.compute.internal"}, {"name": "thread", "value": "48014-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_accept"}]}