{"name": "Verify that the order is not accepted if passing invalid order id.", "status": "passed", "description": "Verify that 404 code is returned for PUT request if order id is invalid.", "start": 1742244739011, "stop": 1742244740064, "uuid": "1f8c598e-a524-45a3-9fb4-783229b30ca2", "historyId": "c2747012e829fe1355b49ae5db3fd43d", "testCaseId": "c2747012e829fe1355b49ae5db3fd43d", "fullName": "tests.test_order.TestOrderAccept#test_accept_order_not_existing_order_id_not_accepted", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "ip-192-168-100-6.eu-north-1.compute.internal"}, {"name": "thread", "value": "63648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}