{"name": "Verify that the order id is not returned if passing invalid track number.", "status": "passed", "description": "Verify that 404 code is returned for GET request if passing invalid track number.", "start": 1742244746410, "stop": 1742244746835, "uuid": "ad929cde-69c0-45e5-be4b-b075ed34399b", "historyId": "519494c90d2656763e42bfee45be4991", "testCaseId": "519494c90d2656763e42bfee45be4991", "fullName": "tests.test_order.TestOrderGetByID#test_get_order_id_by_invalid_track_number_not_returned", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderGetByID"}, {"name": "host", "value": "ip-192-168-100-6.eu-north-1.compute.internal"}, {"name": "thread", "value": "63648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}